---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Me dice la cantidad de reservas de un libro
  checked: false
- value: Me dice la suma de la cantidad de reservas de todas las bibliotecas
  checked: false
- value: Me dice la suma de la cantidad de reservas de una biblioteca específica
  checked: false
- value: Ninguna de las anteriores
  checked: false
